### ISSUE TITLE
max number of results — size parameter

### ISSUE THREAD

**Issue by sduquemesa** [inspirehep/rest-api-doc#14]
When I try to get a page with the number of results set to 1000 (the max number of results allowed by the documentation API), i.e. the parameter `size=1000`, a 502 bad gateway error is returned.

This is the GET request:
https://inspirehep.net/api/literature?q=cn+cms+or+cn+atlas+or+cn+lhcb+or+cn+alice&sort=mostrecent&page=1&size=1000

**Comment by michamos** [comment]
It being allowed in principle doesn't mean it's a good idea. LHC collaboration records are huge (due to the large number of authors), so the time required to generate the response may exceed our server timeout (currently set to 2 min).

There are several ways you could make this work:
* if you don't need the full record metadata, you should look into [filtering](https://github.com/inspirehep/rest-api-doc#metadata-filtering) to get only the fields you need,
* you should use [pagination](https://github.com/inspirehep/rest-api-doc#pagination) together with a (much) smaller `size`, which you'll need to do anyhow as there are [more than 1000 papers](https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=cn%20atlas%20or%20cn%20lhcb%20or%20cn%20cms%20or%20cn%20alice) matching your query.
